# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ARKitExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ARKitExample
  pod 'Alamofire'
  # AWSCore
  pod 'AWSS3'
  # pod 'AssimpKit', :git => 'https://github.com/dmsurti/AssimpKit.git'

  # target 'ARKitExampleTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end
  #
  # target 'ARKitExampleUITests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end
